FROM golang:1.18.4-alpine3.16
WORKDIR /app
COPY . .
RUN go build -o blockchain_server blockchain_server/blockchain_server.go 




EXPOSE 9000

CMD ["go", "run", "/app/blockchain_server/.", "-port", "9000"]
