# docker-compose.yml
version: '3.8'
services:
  blockchain_server:
    build:
      context: .
      dockerfile: Dockerfile.blockchain_server
    ports:
      - 9000:9000
    networks:
      vpcbr:
        ipv4_address: 172.28.0.1
  wallet:
    build:
      context: .
      dockerfile: Dockerfile.wallet
    ports:
      - 8080:8080
    networks:
     vpcbr:
        ipv4_address: 172.28.0.2
networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 172.28.0.0/16
         gateway: 172.28.0.254
        
     