# build stage
FROM golang:1.18.4-alpine3.16 
WORKDIR /app
COPY . .
RUN go build -o blockchain_server blockchain_server/blockchain_server.go 


ARG BLOCKCHAIN_SERVER_PORT
EXPOSE ${BLOCKCHAIN_SERVER_PORT}

CMD ["go", "run", "/app/blockchain_server/.", "-port", ${BLOCKCHAIN_SERVER_PORT}]
